"""addresses table

Revision ID: c7f3f5794ebe
Revises: b3b5457baf90
Create Date: 2019-02-02 14:59:45.793440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f3f5794ebe'
down_revision = 'b3b5457baf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('zipcode', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address'), 'addresses', ['address'], unique=False)
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_name'), 'addresses', ['name'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_zipcode'), 'addresses', ['zipcode'], unique=False)
    op.drop_index('ix_address_address', table_name='address')
    op.drop_index('ix_address_city', table_name='address')
    op.drop_index('ix_address_name', table_name='address')
    op.drop_index('ix_address_state', table_name='address')
    op.drop_index('ix_address_zipcode', table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_zipcode', 'address', ['zipcode'], unique=False)
    op.create_index('ix_address_state', 'address', ['state'], unique=False)
    op.create_index('ix_address_name', 'address', ['name'], unique=False)
    op.create_index('ix_address_city', 'address', ['city'], unique=False)
    op.create_index('ix_address_address', 'address', ['address'], unique=False)
    op.drop_index(op.f('ix_addresses_zipcode'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_name'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
